# Generated by Django 5.2.3 on 2025-07-03 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="post",
            old_name="tittle",
            new_name="title",
        ),
    ]
