# Generated by Django 5.2.3 on 2025-07-03 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_rename_tittle_post_title"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="post",
            options={"ordering": ("created_at",)},
        ),
        migrations.RenameField(
            model_name="post",
            old_name="contact",
            new_name="content",
        ),
    ]
